import "./globals.css";
import Main from "./Main";

export const metadata = {
  title: "Facturas La Herramienta",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Main>{children}</Main>
      </body>
    </html>
  );
}
